#!/usr/bin/tclsh
# ~/TktkofficeDir/tkofficeDir.tcl
# Main launcher prog for TktkofficeDir Business Software
# Installation requirements: Tcl/Tk library, PostgreSQL database
# Updated: 16Sep 19

set tkofficeDir [file normalize [file dirname [info script]]]
set confDir [file join $tkofficeDir conf]
set confFile [file join $confDir config.tcl]
set progDir [file join $tkofficeDir prog]
set spoolDir [file join $tkofficeDir spool]
set texDir [file join $tkofficeDir tex]
set dumpDir [file join $tkofficeDir dumps]
set makeConfig [file join $progDir makeConfig.tcl]
set texVorlage [file join $texDir rechnung-vorlage.tex]

if [catch {source $confFile}] {
  set dbname "Datenbankname eingeben"
  set dbuser "Nutzername eingeben"
  source [file join $progDir tkoffice-gui.tcl]
  after 7000 {
    .n select 3
  }
  NewsHandler::QueryNews "Keine Konfigurationsdatei gefunden. Sie müssen das Programm erst einrichten." red

} else {

  source [file join $progDir tkoffice-gui.tcl]
}

