#!/usr/bin/tclsh
# ~/TkAuftrag/auftrag.tcl
# Main launcher prog for TkAuftrag Business Software
# Installation requirements: Tcl/Tk library, PostgreSQL database
# Updated: 16Sep 19

set auftragDir [file normalize [file dirname [info script]]]
set confDir [file join $auftragDir conf]
set confFile [file join $confDir config.tcl]
set progDir [file join $auftragDir prog]
set spoolDir [file join $auftragDir spool]
set makeConfig [file join $progDir makeConfig.tcl]

if [catch {source $confFile}] {
  set dbname "Datenbankname eingeben"
  set dbuser "Nutzername eingeben"
  source [file join $progDir tkoffice-gui.tcl]
  after 7000 {
    .n select 3
  }
  NewsHandler::QueryNews "Keine Konfigurationsdatei gefunden. Sie müssen das Programm erst einrichten." red

} else {

  source [file join $progDir tkoffice-gui.tcl]
}

